name: create a new task
method: POST
url: http://localhost:3000/tasks
body:
  content: |-
    {
      "title": "Learn NestJS",
      "description": "Complete the NestJS course",
      "status": "OPEN",
      "userId": "d9361d8a-7cc6-49ad-b743-6b1ea0951401",
      "labels": [
        {
          "name": "urgent"
        }
      ]
    }
  content_type: application/json
headers:
- name: content-type
  value: application/json
