name: update task status
method: PATCH
url: http://localhost:3000/tasks/:id
body:
  content: |-
    {
      "status": "IN_PROGRESS"
    }
  content_type: application/json
headers:
- name: content-type
  value: application/json
path_params:
- name: id
  value: 4d450375-8c61-4710-b55b-f4fc7137100e
